
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache \
    networkmanager \
    networkmanager-cli \
    dbus \
    tini \
    udev \
    eudev-libs

RUN addgroup node dialout && \
    chown -R node:node /app

COPY --from=builder /app/node_modules ./node_modules

COPY . .

EXPOSE 3001

USER node

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["npm", "start"]
